### ISSUE TITLE
non-node projects

### ISSUE THREAD

**Issue by maximilianh** [politiken-journalism/scale-color-perceptual#2]
Hi, sorry if this is a stupid question for a Javascript expert, but how would I use this in the browser? Do I need to switch my whole project to browserify ? Or is there  a way to convert an npm package to a standalone js file?

**Comment by emilbayes** [comment]
You can build it as a "standalone" module with Browserify also, but otherwise I'm not sure. See how here: https://github.com/browserify/browserify-handbook#standalone

With standalone you would only ever have to do this once, unless you wanted to update the library. But it's pretty much done, so I don't think it will ever change. There might also be other ways to build UMD

**Comment by emilbayes** [comment]
For example doing this:

```sh
# Browser from the root of the project
browserify --standalone scale.color.perceptual --output scale-color-perceptual.js browser.js
```

I can do:

```html
<script src="scale-color-perceptual.js"></script>
```

```js
scale.color.perceptual.plasma(1) // "#f0f724"
```

**Comment by maximilianh** [comment]
Awesome! This was pretty simple, I just had to learn how to install npm and
then browserify.

You may want to provide the output of this as part of the git repo. Other
people may find it useful.

Thanks!

>

**Comment by maximilianh** [comment]
I wrote a little wrapper to make it look like the other palette
functions out there:

   function makePercPalette(palName, n) {
        /* palettes from
https://github.com/politiken-journalism/scale-color-perceptual */
        var pal = [];
        var step = 1/(n-1);

        var func = null;
        switch (palName) {
            case 'inferno' : func =  scale.color.perceptual.inferno; break;
            case 'viridis' : func =  scale.color.perceptual.viridis; break;
            case 'magma' : func =  scale.color.perceptual.magma; break;
            case 'plasma' : func =  scale.color.perceptual.plasma; break;
        }

        for (let x=0; x<1.0000000001; x+=step) {
            pal.push(func(x));
        }

        return pal;
    }

**Comment by maximilianh** [comment]
it should be <= 1.0 and not <1.00000001 otherwise seems to work even though I still have a feeling that I have a 1-off error in there somewhere... anyhow, my issue is solved, thanks for your quick reply!
